In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
import joblib

In [6]:
 print("knn")
# 1. 데이터 준비
col_names = ['age', 'sex',
             'job', 'hobby',
             'Class']

# csv 파일에서 DataFrame을 생성
dataset = pd.read_csv('shopknn.csv', encoding='UTF-8', header=None, names=col_names)

# DataFrame 확인
print(dataset.shape)  # (row개수, column개수)
print(dataset.info())  # 데이터 타입, row 개수, column 개수, 컬럼 데이터 타입
print(dataset.describe())  # 요약 통계 정보
print(dataset.iloc[0:5])  # dataset.head()
print(dataset.iloc[-5:])  # dataset.tail()

knn
(126, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     126 non-null    int64
 1   sex     126 non-null    int64
 2   job     126 non-null    int64
 3   hobby   126 non-null    int64
 4   Class   126 non-null    int64
dtypes: int64(5)
memory usage: 5.0 KB
None
              age         sex         job       hobby       Class
count  126.000000  126.000000  126.000000  126.000000  126.000000
mean    35.468254    1.444444    2.357143    2.452381    2.587302
std     13.310860    0.498888    0.924894    1.142679    1.154261
min     20.000000    1.000000    1.000000    1.000000    1.000000
25%     24.000000    1.000000    2.000000    1.000000    1.000000
50%     28.000000    1.000000    3.000000    3.000000    3.000000
75%     48.750000    2.000000    3.000000    3.000000    4.000000
max     60.000000    2.000000    4.000000    4.000000    4.000000
 

In [7]:
# X = 전체 행, 마지막 열 제외한 모든 열 데이터 -> n차원 공간의 포인트
X = dataset.iloc[:, :-1].to_numpy()  # DataFrame을 np.ndarray로 변환
print(X)

# y = 전체 행, 마지막 열 데이터
y = dataset.iloc[:, 4].to_numpy()
print(y)

[[28  2  2  2]
 [25  2  2  2]
 [22  2  2  2]
 [22  2  2  2]
 [22  2  2  2]
 [22  2  2  4]
 [23  2  2  3]
 [24  2  2  4]
 [25  2  3  3]
 [26  2  3  3]
 [27  1  3  2]
 [28  1  3  4]
 [29  1  3  2]
 [24  1  3  4]
 [25  1  3  2]
 [26  1  3  3]
 [27  1  3  2]
 [24  1  3  4]
 [25  1  3  3]
 [26  1  3  2]
 [27  1  3  3]
 [20  2  3  1]
 [22  2  4  1]
 [32  2  3  4]
 [20  2  3  1]
 [33  2  3  1]
 [49  2  2  1]
 [50  2  2  1]
 [52  2  4  3]
 [52  2  2  4]
 [53  2  2  1]
 [54  2  2  2]
 [55  1  1  4]
 [56  1  3  3]
 [57  1  4  2]
 [58  1  1  4]
 [45  1  1  4]
 [46  1  1  3]
 [47  1  1  3]
 [48  1  1  3]
 [49  1  3  3]
 [44  1  1  3]
 [45  1  4  3]
 [46  2  3  1]
 [47  2  3  1]
 [48  2  3  1]
 [49  2  4  1]
 [23  2  3  1]
 [24  2  3  1]
 [24  1  3  3]
 [25  1  3  2]
 [25  1  3  2]
 [25  1  4  3]
 [26  1  1  2]
 [26  1  1  3]
 [27  1  1  3]
 [27  1  1  4]
 [28  1  1  4]
 [28  1  1  1]
 [29  1  1  1]
 [29  1  1  2]
 [20  1  1  1]
 [20  1  1  3]
 [22  2  3  1]
 [22  2  3  1]
 [22  2  3  1]
 [22  2  3

In [8]:
# 전체 데이터 세트를 학습 세트(training set)와 검증 세트(test set)로 나눔
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=23)
print(len(X_train), len(X_test))

print(X_train[:3])
print(y_train[:3])

100 26
[[46  1  4  3]
 [54  2  2  4]
 [49  1  3  3]]
[3 4 4]


In [9]:
# k-NN 분류기를 생성
classifier = KNeighborsClassifier(n_neighbors=5)
# 분류기 학습
classifier.fit(X_train, y_train)

# 예측
y_pred = classifier.predict(X_test)
print(len(X_test))
print(y_pred)
print(len(y_pred))

from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, y_pred)))

26
[4 1 3 1 3 4 2 2 4 3 1 4 4 2 1 3 3 1 4 2 1 1 2 4 1 1]
26
예측 정확도: 0.5769


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [10]:
# 모델 저장


joblib.dump(classifier, './shopknn.pkl')

['./shopknn.pkl']

In [11]:
# 모델 불러오기
loaded_model = joblib.load('./shopknn.pkl')
# 예측
loaded_pred = loaded_model.predict(X_test)
print(loaded_pred)

[4 1 3 1 3 4 2 2 4 3 1 4 4 2 1 3 3 1 4 2 1 1 2 4 1 1]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
